const countriesByContinent = {
  Europe:
  [ 'Andorra',
    'Albania',
    'Austria',
    'Åland',
    'Bosnia and Herzegovina',
    'Belgium',
    'Bulgaria',
    'Belarus',
    'Switzerland',
    'Cyprus',
    'Czechia',
    'Germany',
    'Denmark',
    'Estonia',
    'Spain',
    'Finland',
    'Faroe Islands',
    'France',
    'United Kingdom',
    'Guernsey',
    'Gibraltar',
    'Greece',
    'Croatia',
    'Hungary',
    'Ireland',
    'Isle of Man',
    'Iceland',
    'Italy',
    'Jersey',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Monaco',
    'Moldova, Republic of',
    'Montenegro',
    'Macedonia',
    'Malta',
    'Netherlands',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Serbia',
    'Russia',
    'Sweden',
    'Slovenia',
    'Svalbard and Jan Mayen',
    'Slovakia',
    'San Marino',
    'Ukraine',
    'Vatican City',
    'Kosovo' ],
  Asia:
  [ 'United Arab Emirates',
    'Afghanistan',
    'Armenia',
    'Azerbaijan',
    'Bangladesh',
    'Bahrain',
    'Brunei',
    'Bhutan',
    'Cocos [Keeling] Islands',
    'China',
    'Georgia',
    'Hong Kong',
    'Indonesia',
    'Israel',
    'India',
    'British Indian Ocean Territory',
    'Iraq',
    'Iran',
    'Jordan',
    'Japan',
    'Kyrgyzstan',
    'Cambodia',
    'North Korea',
    'South Korea',
    'Kuwait',
    'Kazakhstan',
    'Lao People\'s Democratic Republic',
    'Lebanon',
    'Sri Lanka',
    'Myanmar [Burma]',
    'Mongolia',
    'Macao',
    'Maldives',
    'Malaysia',
    'Nepal',
    'Oman',
    'Philippines',
    'Pakistan',
    'Palestine',
    'Qatar',
    'Saudi Arabia',
    'Singapore',
    'Syria',
    'Thailand',
    'Tajikistan',
    'Turkmenistan',
    'Turkey',
    'Taiwan',
    'Uzbekistan',
    'Vietnam',
    'Yemen' ],
  NorthAmerica:
  [ 'Antigua and Barbuda',
    'Anguilla',
    'Aruba',
    'Barbados',
    'Saint Barthélemy',
    'Bermuda',
    'Bonaire',
    'Bahamas',
    'Belize',
    'Canada',
    'Costa Rica',
    'Cuba',
    'Curacao',
    'Dominica',
    'Dominican Republic',
    'Grenada',
    'Greenland',
    'Guadeloupe',
    'Guatemala',
    'Honduras',
    'Haiti',
    'Jamaica',
    'Saint Kitts and Nevis',
    'Cayman Islands',
    'Saint Lucia',
    'Saint Martin',
    'Martinique',
    'Montserrat',
    'Mexico',
    'Nicaragua',
    'Panama',
    'Saint Pierre and Miquelon',
    'Puerto Rico',
    'El Salvador',
    'Sint Maarten',
    'Turks and Caicos Islands',
    'Trinidad and Tobago',
    'USA',
    'Saint Vincent and the Grenadines',
    'British Virgin Islands',
    'U.S. Virgin Islands' ],
  Africa:
  [ 'Angola',
    'Burkina Faso',
    'Burundi',
    'Benin',
    'Botswana',
    'Democratic Republic of the Congo',
    'Central African Republic',
    'Republic of the Congo',
    'Ivory Coast',
    'Cameroon',
    'Cape Verde',
    'Djibouti',
    'Algeria',
    'Egypt',
    'Western Sahara',
    'Eritrea',
    'Ethiopia',
    'Gabon',
    'Ghana',
    'Gambia',
    'Guinea',
    'Equatorial Guinea',
    'Guinea-Bissau',
    'Kenya',
    'Comoros',
    'Liberia',
    'Lesotho',
    'Libya',
    'Morocco',
    'Madagascar',
    'Mali',
    'Mauritania',
    'Mauritius',
    'Malawi',
    'Mozambique',
    'Namibia',
    'Niger',
    'Nigeria',
    'Réunion',
    'Rwanda',
    'Seychelles',
    'Sudan',
    'Saint Helena',
    'Sierra Leone',
    'Senegal',
    'Somalia',
    'South Sudan',
    'São Tomé and Príncipe',
    'Swaziland',
    'Chad',
    'Togo',
    'Tunisia',
    'Tanzania',
    'Uganda',
    'Mayotte',
    'South Africa',
    'Zambia',
    'Zimbabwe' ],
  Antarctica:
  [ 'Antarctica',
    'Bouvet Island',
    'South Georgia and the South Sandwich Islands',
    'Heard Island and McDonald Islands',
    'French Southern Territories' ],
  SouthAmerica:
  [ 'Argentina',
    'Bolivia',
    'Brazil',
    'Chile',
    'Colombia',
    'Ecuador',
    'Falkland Islands',
    'French Guiana',
    'Guyana',
    'Peru',
    'Paraguay',
    'Suriname',
    'Uruguay',
    'Venezuela' ],
  Oceania:
  [ 'American Samoa',
    'Australia',
    'Cook Islands',
    'Christmas Island',
    'Fiji',
    'Micronesia',
    'Guam',
    'Kiribati',
    'Marshall Islands',
    'Northern Mariana Islands',
    'New Caledonia',
    'Norfolk Island',
    'Nauru',
    'Niue',
    'New Zealand',
    'French Polynesia',
    'Papua New Guinea',
    'Pitcairn Islands',
    'Palau',
    'Solomon Islands',
    'Tokelau',
    'East Timor',
    'Tonga',
    'Tuvalu',
    'U.S. Minor Outlying Islands',
    'Vanuatu',
    'Wallis and Futuna',
    'Samoa' ]
}

module.exports = { countriesByContinent }
